print("hello world")
print("riley is a breaking bad hater")
print("eric kim is mean")
print(4*10)
print(" Riley once had a father, then his father attempted to blow up his house. the end")
print("FINN HORNER")
print("mrs white")
print("King's high school")
print("iam 15")
print("i have at least 80 days")
print(80*24)
print("2047")
print("i will be 115")
print(658/7)
print("53 years ago")
print("Sea of thieves")
print("mrs whites cool class")
print(5+5)
print(4/5) #divison
print(10000+10000) #multiplaction